local reportedControls = {}

local controlsCollection = {
    { control = 0, desc = "V" },
    { control = 1, desc = "MOUSE RIGHT" },
    { control = 2, desc = "MOUSE DOWN" },
    { control = 3, desc = "(NONE)" },
    { control = 4, desc = "MOUSE DOWN" },
    { control = 5, desc = "(NONE)" },
    { control = 6, desc = "MOUSE RIGHT" },
    { control = 7, desc = "(NONE)" },
    { control = 8, desc = "S" },
    { control = 9, desc = "D" },
    { control = 10, desc = "PAGEUP" },
    { control = 11, desc = "PAGEDOWN" },
    { control = 12, desc = "MOUSE DOWN" },
    { control = 13, desc = "MOUSE RIGHT" },
    { control = 14, desc = "SCROLLWHEEL DOWN" },
    { control = 15, desc = "SCROLLWHEEL UP" },
    { control = 16, desc = "SCROLLWHEEL DOWN" },
    { control = 17, desc = "SCROLLWHEEL UP" },
    { control = 18, desc = "ENTER / LEFT MOUSE BUTTON / SPACEBAR" },
    { control = 19, desc = "LEFT ALT" },
    { control = 20, desc = "Z" },
    { control = 21, desc = "LEFT SHIFT" },
    { control = 22, desc = "SPACEBAR" },
    { control = 23, desc = "F" },
    { control = 24, desc = "LEFT MOUSE BUTTON" },
    { control = 25, desc = "RIGHT MOUSE BUTTON" },
    { control = 26, desc = "C" },
    { control = 27, desc = "ARROW UP / SCROLLWHEEL BUTTON (PRESS)" },
    { control = 28, desc = "(NONE)" },
    { control = 29, desc = "B" },
    { control = 30, desc = "D" },
    { control = 31, desc = "S" },
    { control = 32, desc = "W" },
    { control = 33, desc = "S" },
    { control = 34, desc = "A" },
    { control = 35, desc = "D" },
    { control = 36, desc = "LEFT CTRL" },
    { control = 37, desc = "TAB" },
    { control = 38, desc = "E" },
    { control = 39, desc = "SCROLLWHEEL DOWN" },
    { control = 40, desc = "SCROLLWHEEL UP" },
    { control = 41, desc = "SCROLLWHEEL DOWN" },
    { control = 42, desc = "SCROLLWHEEL UP" },
    { control = 43, desc = "SCROLLWHEEL DOWN" },
    { control = 44, desc = "Q" },
    { control = 45, desc = "R" },
    { control = 46, desc = "E" },
    { control = 47, desc = "G" },
    { control = 48, desc = "Z" },
    { control = 49, desc = "F" },
    { control = 50, desc = "SCROLLWHEEL DOWN" },
    { control = 51, desc = "E" },
    { control = 52, desc = "Q" },
    { control = 53, desc = "(NONE)" },
    { control = 54, desc = "E" },
    { control = 55, desc = "SPACEBAR" },
    { control = 56, desc = "F9" },
    { control = 57, desc = "F10" },
    { control = 58, desc = "G" },
    { control = 59, desc = "D" },
    { control = 60, desc = "LEFT CTRL" },
    { control = 61, desc = "LEFT SHIFT" },
    { control = 62, desc = "LEFT CTRL" },
    { control = 63, desc = "A" },
    { control = 64, desc = "D" },
    { control = 65, desc = "(NONE)" },
    { control = 66, desc = "MOUSE RIGHT" },
    { control = 67, desc = "MOUSE DOWN" },
    { control = 68, desc = "RIGHT MOUSE BUTTON" },
    { control = 69, desc = "LEFT MOUSE BUTTON" },
    { control = 70, desc = "RIGHT MOUSE BUTTON" },
    { control = 71, desc = "W" },
    { control = 72, desc = "S" },
    { control = 73, desc = "X" },
    { control = 74, desc = "H" },
    { control = 75, desc = "F" },
    { control = 76, desc = "SPACEBAR" },
    { control = 77, desc = "W" },
    { control = 78, desc = "S" },
    { control = 79, desc = "C" },
    { control = 80, desc = "R" },
    { control = 81, desc = "SCROLLWHEEL DOWN" },
    { control = 82, desc = "," },
    { control = 83, desc = "=" },
    { control = 84, desc = "-" },
    { control = 85, desc = "Q" },
    { control = 86, desc = "E" },
    { control = 87, desc = "W" },
    { control = 88, desc = "S" },
    { control = 89, desc = "A" },
    { control = 90, desc = "D" },
    { control = 91, desc = "RIGHT MOUSE BUTTON" },
    { control = 92, desc = "LEFT MOUSE BUTTON" },
    { control = 93, desc = "(NONE)" },
    { control = 94, desc = "(NONE)" },
    { control = 95, desc = "MOUSE DOWN" },
    { control = 96, desc = "NUMPAD- / SCROLLWHEEL UP" },
    { control = 97, desc = "NUMPAD+ / SCROLLWHEEL DOWN" },
    { control = 98, desc = "MOUSE RIGHT" },
    { control = 99, desc = "SCROLLWHEEL UP" },
    { control = 100, desc = "[" },
    { control = 101, desc = "H" },
    { control = 102, desc = "SPACEBAR" },
    { control = 103, desc = "E" },
    { control = 104, desc = "H" },
    { control = 105, desc = "X" },
    { control = 106, desc = "LEFT MOUSE BUTTON" },
    { control = 107, desc = "NUMPAD 6" },
    { control = 108, desc = "NUMPAD 4" },
    { control = 109, desc = "NUMPAD 6" },
    { control = 110, desc = "NUMPAD 5" },
    { control = 111, desc = "NUMPAD 8" },
    { control = 112, desc = "NUMPAD 5" },
    { control = 113, desc = "G" },
    { control = 114, desc = "RIGHT MOUSE BUTTON" },
    { control = 115, desc = "SCROLLWHEEL UP" },
    { control = 116, desc = "[" },
    { control = 117, desc = "NUMPAD 7" },
    { control = 118, desc = "NUMPAD 9" },
    { control = 119, desc = "E" },
    { control = 120, desc = "X" },
    { control = 121, desc = "INSERT" },
    { control = 122, desc = "LEFT MOUSE BUTTON" },
    { control = 123, desc = "NUMPAD 6" },
    { control = 124, desc = "NUMPAD 4" },
    { control = 125, desc = "NUMPAD 6" },
    { control = 126, desc = "NUMPAD 5" },
    { control = 127, desc = "NUMPAD 8" },
    { control = 128, desc = "NUMPAD 5" },
    { control = 129, desc = "W" },
    { control = 130, desc = "S" },
    { control = 131, desc = "LEFT SHIFT" },
    { control = 132, desc = "LEFT CTRL" },
    { control = 133, desc = "A" },
    { control = 134, desc = "D" },
    { control = 135, desc = "LEFT MOUSE BUTTON" },
    { control = 136, desc = "W" },
    { control = 137, desc = "CAPSLOCK" },
    { control = 138, desc = "Q" },
    { control = 139, desc = "S" },
    { control = 140, desc = "R" },
    { control = 141, desc = "Q" },
    { control = 142, desc = "LEFT MOUSE BUTTON" },
    { control = 143, desc = "SPACEBAR" },
    { control = 144, desc = "F / LEFT MOUSE BUTTON" },
    { control = 145, desc = "F" },
    { control = 146, desc = "D" },
    { control = 147, desc = "A" },
    { control = 148, desc = "D" },
    { control = 149, desc = "S" },
    { control = 150, desc = "W" },
    { control = 151, desc = "S" },
    { control = 152, desc = "Q" },
    { control = 153, desc = "E" },
    { control = 154, desc = "X" },
    { control = 155, desc = "LEFT SHIFT" },
    { control = 156, desc = "(NONE)" },
    { control = 157, desc = "1" },
    { control = 158, desc = "2" },
    { control = 159, desc = "6" },
    { control = 160, desc = "3" },
    { control = 161, desc = "7" },
    { control = 162, desc = "8" },
    { control = 163, desc = "9" },
    { control = 164, desc = "4" },
    { control = 165, desc = "5" },
    { control = 166, desc = "F5" },
    { control = 167, desc = "F6" },
    { control = 168, desc = "F7" },
    { control = 169, desc = "F8 (CONSOLE)" },
    { control = 170, desc = "F3" },
    { control = 171, desc = "CAPSLOCK" },
    { control = 172, desc = "ARROW UP" },
    { control = 173, desc = "ARROW DOWN" },
    { control = 174, desc = "ARROW LEFT" },
    { control = 175, desc = "ARROW RIGHT" },
    { control = 176, desc = "ENTER / LEFT MOUSE BUTTON" },
    { control = 177, desc = "BACKSPACE / ESC / RIGHT MOUSE BUTTON" },
    { control = 178, desc = "DELETE" },
    { control = 179, desc = "SPACEBAR" },
    { control = 180, desc = "SCROLLWHEEL DOWN" },
    { control = 181, desc = "SCROLLWHEEL UP" },
    { control = 182, desc = "L" },
    { control = 183, desc = "G" },
    { control = 184, desc = "E" },
    { control = 185, desc = "F" },
    { control = 186, desc = "X" },
    { control = 187, desc = "ARROW DOWN" },
    { control = 188, desc = "ARROW UP" },
    { control = 189, desc = "ARROW LEFT" },
    { control = 190, desc = "ARROW RIGHT" },
    { control = 191, desc = "ENTER" },
    { control = 192, desc = "TAB" },
    { control = 193, desc = "(NONE)" },
    { control = 194, desc = "BACKSPACE" },
    { control = 195, desc = "D" },
    { control = 196, desc = "S" },
    { control = 197, desc = "]" },
    { control = 198, desc = "SCROLLWHEEL DOWN" },
    { control = 199, desc = "P" },
    { control = 200, desc = "ESC" },
    { control = 201, desc = "ENTER / NUMPAD ENTER" },
    { control = 202, desc = "BACKSPACE / ESC" },
    { control = 203, desc = "SPACEBAR" },
    { control = 204, desc = "TAB" },
    { control = 205, desc = "Q" },
    { control = 206, desc = "E" },
    { control = 207, desc = "PAGE DOWN" },
    { control = 208, desc = "PAGE UP" },
    { control = 209, desc = "LEFT SHIFT" },
    { control = 210, desc = "LEFT CONTROL" },
    { control = 211, desc = "TAB" },
    { control = 212, desc = "HOME" },
    { control = 213, desc = "HOME" },
    { control = 214, desc = "DELETE" },
    { control = 215, desc = "ENTER" },
    { control = 216, desc = "SPACEBAR" },
    { control = 217, desc = "CAPSLOCK" },
    { control = 218, desc = "D" },
    { control = 219, desc = "S" },
    { control = 220, desc = "MOUSE RIGHT" },
    { control = 221, desc = "MOUSE DOWN" },
    { control = 222, desc = "RIGHT MOUSE BUTTON" },
    { control = 223, desc = "LEFT MOUSE BUTTON" },
    { control = 224, desc = "LEFT CTRL" },
    { control = 225, desc = "RIGHT MOUSE BUTTON" },
    { control = 226, desc = "(NONE)" },
    { control = 227, desc = "(NONE)" },
    { control = 228, desc = "(NONE)" },
    { control = 229, desc = "LEFT MOUSE BUTTON" },
    { control = 230, desc = "(NONE)" },
    { control = 231, desc = "(NONE)" },
    { control = 232, desc = "W" },
    { control = 233, desc = "S" },
    { control = 234, desc = "A" },
    { control = 235, desc = "D" },
    { control = 236, desc = "V" },
    { control = 237, desc = "LEFT MOUSE BUTTON" },
    { control = 238, desc = "RIGHT MOUSE BUTTON" },
    { control = 239, desc = "(NONE)" },
    { control = 240, desc = "(NONE)" },
    { control = 241, desc = "SCROLLWHEEL UP" },
    { control = 242, desc = "SCROLLWHEEL DOWN" },
    { control = 243, desc = "~ / `" },
    { control = 244, desc = "M" },
    { control = 245, desc = "T" },
    { control = 246, desc = "Y" },
    { control = 247, desc = "(NONE)" },
    { control = 248, desc = "(NONE)" },
    { control = 249, desc = "N" },
    { control = 250, desc = "R" },
    { control = 251, desc = "F" },
    { control = 252, desc = "X" },
    { control = 253, desc = "C" },
    { control = 254, desc = "LEFT SHIFT" },
    { control = 255, desc = "SPACEBAR" },
    { control = 256, desc = "DELETE" },
    { control = 257, desc = "LEFT MOUSE BUTTON" },
    { control = 258, desc = "(NONE)" },
    { control = 259, desc = "(NONE)" },
    { control = 260, desc = "(NONE)" },
    { control = 261, desc = "SCROLLWHEEL UP" },
    { control = 262, desc = "SCROLLWHEEL DOWN" },
    { control = 263, desc = "R" },
    { control = 264, desc = "Q" },
    { control = 265, desc = "(NONE)" },
    { control = 266, desc = "D" },
    { control = 267, desc = "D" },
    { control = 268, desc = "S" },
    { control = 269, desc = "S" },
    { control = 270, desc = "MOUSE RIGHT" },
    { control = 271, desc = "MOUSE RIGHT" },
    { control = 272, desc = "MOUSE DOWN" },
    { control = 273, desc = "MOUSE DOWN" },
    { control = 274, desc = "[" },
    { control = 275, desc = "[" },
    { control = 276, desc = "[" },
    { control = 277, desc = "[" },
    { control = 278, desc = "D" },
    { control = 279, desc = "D" },
    { control = 280, desc = "LEFT CTRL" },
    { control = 281, desc = "LEFT CTRL" },
    { control = 282, desc = "MOUSE RIGHT" },
    { control = 283, desc = "MOUSE RIGHT" },
    { control = 284, desc = "MOUSE RIGHT" },
    { control = 285, desc = "MOUSE RIGHT" },
    { control = 286, desc = "MOUSE RIGHT" },
    { control = 287, desc = "MOUSE RIGHT" },
    { control = 288, desc = "F1" },
    { control = 289, desc = "F2" },
    { control = 290, desc = "MOUSE RIGHT" },
    { control = 291, desc = "MOUSE DOWN" },
    { control = 292, desc = "(NONE)" },
    { control = 293, desc = "(NONE)" },
    { control = 294, desc = "(NONE)" },
    { control = 295, desc = "(NONE)" },
    { control = 296, desc = "DELETE" },
    { control = 297, desc = "DELETE" },
    { control = 298, desc = "SPACEBAR" },
    { control = 299, desc = "ARROW DOWN" },
    { control = 300, desc = "ARROW UP" },
    { control = 301, desc = "M" },
    { control = 302, desc = "S" },
    { control = 303, desc = "U" },
    { control = 304, desc = "H" },
    { control = 305, desc = "B" },
    { control = 306, desc = "N" },
    { control = 307, desc = "ARROW RIGHT" },
    { control = 308, desc = "ARROW LEFT" },
    { control = 309, desc = "T" },
    { control = 310, desc = "R" },
    { control = 311, desc = "K" },
    { control = 312, desc = "[" },
    { control = 313, desc = "]" },
    { control = 314, desc = "NUMPAD +" },
    { control = 315, desc = "NUMPAD -" },
    { control = 316, desc = "PAGE UP" },
    { control = 317, desc = "PAGE DOWN" },
    { control = 318, desc = "F5" },
    { control = 319, desc = "C" },
    { control = 320, desc = "V" },
    { control = 321, desc = "SPACEBAR" },
    { control = 322, desc = "ESC" },
    { control = 323, desc = "X" },
    { control = 324, desc = "C" },
    { control = 325, desc = "V" },
    { control = 326, desc = "LEFT CTRL" },
    { control = 327, desc = "F5" },
    { control = 328, desc = "SPACEBAR" },
    { control = 329, desc = "LEFT MOUSE BUTTON" },
    { control = 330, desc = "LEFT MOUSE BUTTON" },
    { control = 331, desc = "RIGHT MOUSE BUTTON" },
    { control = 332, desc = "MOUSE DOWN" },
    { control = 333, desc = "MOUSE RIGHT" },
    { control = 334, desc = "SCROLLWHEEL DOWN" },
    { control = 335, desc = "SCROLLWHEEL UP" },
    { control = 336, desc = "X" },
    { control = 337, desc = "A" },
    { control = 338, desc = "A" },
    { control = 339, desc = "D" },
    { control = 340, desc = "LEFT SHIFT" },
    { control = 341, desc = "LEFT CTRL" },
    { control = 342, desc = "D" },
    { control = 343, desc = "LEFT CTRL" },
    { control = 344, desc = "F11" },
    { control = 345, desc = "X" },
    { control = 346, desc = "LEFT MOUSE BUTTON" },
    { control = 347, desc = "RIGHT MOUSE BUTTON" },
    { control = 348, desc = "SCROLLWHEEL BUTTON (PRESS)" },
    { control = 349, desc = "TAB" },
    { control = 350, desc = "E" },
    { control = 351, desc = "E" },
    { control = 352, desc = "LEFT SHIFT" },
    { control = 353, desc = "SPACEBAR" },
    { control = 354, desc = "X" },
    { control = 355, desc = "E" },
    { control = 356, desc = "E" },
    { control = 357, desc = "NONE" },
	{ control = 358, desc = "NONE" },
	{ control = 359, desc = "NONE" },
	{ control = 360, desc = "NONE" },
}

CreateThread(function()
    while IsPedDeadOrDying(GetPlayerPed(PlayerId()), true) do
        for controlIndex = 0, 360 do
            local skipControl = false
            
            for _, skippedControl in ipairs(Config.allowedControlsWhileDead) do
                if controlIndex == skippedControl then
                    skipControl = true
                    break
                end
            end
            
            if not skipControl then
                DisableControlAction(0, controlIndex, true)
                if IsDisabledControlJustPressed(0, controlIndex) then

                    local controlDesc = "Unknown"

                    for _, controlData in ipairs(controlsCollection) do
                        if controlData.control == controlIndex then
                            controlDesc = controlData.desc
                            break
                        end
                    end
                    
                    if not reportedControls[controlDesc] then
                        reportedControls[controlDesc] = true
                        TriggerServerEvent('sendToDiscord', Config.Message .. controlIndex .. Config.Message2 .. controlDesc)
                    end
                end
            end
        end
		reportedControls = {}
        Citizen.Wait(0)
    end
end)